-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 7539d8bd1a00a3c1bfd34cdb606d3a6372e83469
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-yaml
    -   id: double-quote-string-fixer
    -   id: end-of-file-fixer
    -   id: name-tests-test
    -   id: trailing-whitespace
-   repo: git://github.com/pre-commit/mirrors-yapf
    sha: v0.11.1
    hooks:
    -   id: yapf
-   repo: git://github.com/FalconSocial/pre-commit-python-sorter
    sha: 1.0.4
    hooks:
    -   id: python-import-sorter
        args:
        - --silent-overwrite
